Sync dockerfiles with newest changes

diff --git a/docker/main-images/el8/Dockerfile b/docker/main-images/el8/Dockerfile
--- a/docker/main-images/el8/Dockerfile
+++ b/docker/main-images/el8/Dockerfile
@@ -1,33 +1,45 @@
 FROM rockylinux:8
 
+# Ensure commands fail on error
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
 # Install dependencies
-RUN yum -y update; yum clean all; \
-    yum -y install git make cmake wget unzip patch which file; \
-    yum -y install gcc gcc-c++ gcc-gfortran; \
-    yum -y install dnf-plugins-core; \
-    yum config-manager --set-enabled powertools; \
-    yum -y install python3 lapack-devel findutils diffutils;
+RUN dnf -y update \
+ && dnf -y install dnf-plugins-core \
+ && dnf config-manager --set-enabled powertools || dnf config-manager --set-enabled PowerTools || true \
+ && dnf -y install epel-release \
+ && dnf -y install \
+      git make cmake wget unzip patch which file \
+      gcc gcc-c++ gcc-gfortran \
+      lapack-devel \
+      python3 python3-devel \
+      findutils diffutils \
+ && dnf clean all
 
 # Create directory structure
-RUN mkdir repo
+RUN mkdir -p /repo
+
+# Copy the coinhsl.tar.gz file into the repo folder
+# COPY ./hsl/coinhsl.tar.gz /repo/coinhsl.tar.gz
 
 # Install PETSc
-RUN cd repo; \
-    wget https://gitlab.com/petsc/petsc/-/archive/v3.20.6/petsc-v3.20.6.tar.gz; \
-    tar -zxvf petsc-v3.20.6.tar.gz; \
-    mv petsc-v3.20.6 petsc; \
-    mkdir petsc-dist; \
-    cd petsc; \
-    ./configure configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 --download-metis --download-mumps --with-mumps-serial=1 --prefix=/repo/petsc-dist; \
-    make;\
-    make install;
+RUN cd /repo \
+ && wget https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.20.6.tar.gz \
+ && tar -zxvf petsc-3.20.6.tar.gz \
+ && mv petsc-3.20.6 petsc \
+ && mkdir petsc-dist \
+ && cd petsc \
+ && ./configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 \
+      --download-metis --download-mumps --with-mumps-serial=1 \
+      --prefix=/repo/petsc-dist \
+ && make \
+ && make install
 
 # Install boost
-RUN cd repo; \
-    wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz; \
-    tar -zxvf boost_1_87_0.tar.gz; \
-    cd ./boost_1_87_0; \
-    sh bootstrap.sh --prefix=/usr/local/; \
-    chmod a+x ./b2; \
-    ./b2 install || true;
-
+RUN cd /repo \
+ && wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz \
+ && tar -zxvf boost_1_87_0.tar.gz \
+ && cd boost_1_87_0 \
+ && sh bootstrap.sh --prefix=/usr/local \
+ && chmod a+x ./b2 \
+ && ./b2 install
diff --git a/docker/main-images/ubuntu2004/Dockerfile b/docker/main-images/ubuntu2004/Dockerfile
--- a/docker/main-images/ubuntu2004/Dockerfile
+++ b/docker/main-images/ubuntu2004/Dockerfile
@@ -1,36 +1,46 @@
 FROM ubuntu:20.04
 
+# Ensure commands fail on error
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+# Set noninteractive apt and timezone
+ENV DEBIAN_FRONTEND=noninteractive
+ENV TZ=America/New_York
+
 # Install dependencies
-RUN apt-get -y update; \
-    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime; \
-    export DEBIAN_FRONTEND=noninteractive; \
-    apt-get -y upgrade; \
-    apt-get -y install ubuntu-dev-tools liblapack-dev libblas-dev unzip; \
-    apt-get -y install gfortran cmake; \
-    apt-get -y install pkg-config bison; \
-    apt-get -y install flex valgrind;
+RUN apt-get update -y \
+ && apt-get upgrade -y \
+ && apt-get install -y \
+      ubuntu-dev-tools unzip cmake pkg-config wget \
+      gfortran liblapack-dev libblas-dev libpython3-dev \
+ && ln -fs /usr/share/zoneinfo/$TZ /etc/localtime \
+ && dpkg-reconfigure -f noninteractive tzdata \
+ && rm -rf /var/lib/apt/lists/*
 
 # Create directory structure
-RUN mkdir repo
+RUN mkdir -p /repo
+
+# Copy the coinhsl.tar.gz file into the repo folder
+# COPY ./hsl/coinhsl.tar.gz /repo/coinhsl.tar.gz
 
 # Install PETSc
-# 3.20.6 is the newest version that works with the PETSc extras
-# included in this repo
-RUN cd repo; \
-    wget https://gitlab.com/petsc/petsc/-/archive/v3.20.6/petsc-v3.20.6.tar.gz; \
-    tar -zxvf petsc-v3.20.6.tar.gz; \
-    mv petsc-v3.20.6 petsc; \
-    mkdir petsc-dist; \
-    cd petsc; \
-    ./configure configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 --download-metis --download-mumps --with-mumps-serial=1 --prefix=/repo/petsc-dist; \
-    make;\
-    make install;
+RUN cd /repo \
+ && wget https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.20.6.tar.gz \
+ && tar -zxvf petsc-3.20.6.tar.gz \
+ && mv petsc-3.20.6 petsc \
+ && mkdir petsc-dist \
+ && cd petsc \
+ && ./configure --with-debug=0 --with-shared=0 --with-mpi=0 --with-fortran-bindings=0 \
+      --download-metis --download-mumps --with-mumps-serial=1 \
+      --prefix=/repo/petsc-dist \
+ && make \
+ && make install
 
 # Install boost
-RUN cd repo; \
-    wget https://boostorg.jfrog.io/artifactory/main/release/1.86.0/source/boost_1_86_0.tar.gz; \
-    tar -zxvf boost_1_86_0.tar.gz; \
-    cd ./boost_1_86_0; \
-    sh bootstrap.sh --prefix=/usr/local/; \
-    chmod a+x ./b2; \
-    ./b2 install || true;
+RUN cd /repo \
+ && wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz \
+ && tar -zxvf boost_1_87_0.tar.gz \
+ && cd boost_1_87_0 \
+ && sh bootstrap.sh --prefix=/usr/local \
+ && chmod a+x ./b2 \
+ && ./b2 install
